"""Generates deterministic incident scenarios."""

from __future__ import annotations
import random
from server.environment.models import Alert
from server.environment.infrastructure import InfrastructureSimulator

EASY_SCENARIOS = [
    {
        "name": "order_service_bad_deploy",
        "root_cause_service": "order-service",
        "root_cause_category": "bad_deployment",
        "severity": "sev2",
        "affected_services": ["order-service", "api-gateway"],
        "correct_remediation": "rollback",
        "alert_service": "order-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 5%",
        "alert_value": "12.3%",
        "alert_threshold": "5%",
        "description": "Order service deployed v2.25.0 with a null pointer bug",
        "bad_deployment_changelog": "Added new payment validation logic with updated null checks",
        "bad_config": None,
        "red_herrings": [],
    },
    {
        "name": "user_db_resource_exhaustion",
        "root_cause_service": "user-db",
        "root_cause_category": "resource_exhaustion",
        "severity": "sev2",
        "affected_services": ["user-db", "user-service", "auth-service"],
        "correct_remediation": "scale_up",
        "alert_service": "user-service",
        "alert_metric": "latency_p99_ms",
        "alert_condition": "latency_p99 > 2000ms",
        "alert_value": "4523ms",
        "alert_threshold": "2000ms",
        "description": "User database ran out of connections",
        "bad_deployment_changelog": None,
        "bad_config": None,
        "red_herrings": [],
    },
    {
        "name": "cache_redis_oom",
        "root_cause_service": "cache-redis",
        "root_cause_category": "resource_exhaustion",
        "severity": "sev3",
        "affected_services": ["cache-redis", "user-service", "product-service"],
        "correct_remediation": "restart",
        "alert_service": "product-service",
        "alert_metric": "latency_p99_ms",
        "alert_condition": "latency_p99 > 500ms",
        "alert_value": "1230ms",
        "alert_threshold": "500ms",
        "description": "Redis cache OOM causing cache misses",
        "bad_deployment_changelog": None,
        "bad_config": None,
        "red_herrings": [],
    },
    {
        "name": "payment_service_deploy_bug",
        "root_cause_service": "payment-service",
        "root_cause_category": "bad_deployment",
        "severity": "sev1",
        "affected_services": ["payment-service", "order-service", "api-gateway"],
        "correct_remediation": "rollback",
        "alert_service": "payment-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 10%",
        "alert_value": "45.2%",
        "alert_threshold": "10%",
        "description": "Payment service deployed with broken gateway integration",
        "bad_deployment_changelog": "Migrated to async request handling for payment gateway calls",
        "bad_config": None,
        "red_herrings": [],
    },
    {
        "name": "notification_oom",
        "root_cause_service": "notification-service",
        "root_cause_category": "resource_exhaustion",
        "severity": "sev3",
        "affected_services": ["notification-service"],
        "correct_remediation": "restart",
        "alert_service": "notification-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 5%",
        "alert_value": "23.1%",
        "alert_threshold": "5%",
        "description": "Notification worker OOMKilled",
        "bad_deployment_changelog": None,
        "bad_config": None,
        "red_herrings": [],
    },
    {
        "name": "auth_service_bad_deploy",
        "root_cause_service": "auth-service",
        "root_cause_category": "bad_deployment",
        "severity": "sev2",
        "affected_services": ["auth-service", "user-service", "api-gateway"],
        "correct_remediation": "rollback",
        "alert_service": "auth-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 5%",
        "alert_value": "28.5%",
        "alert_threshold": "5%",
        "description": "Auth service deployed with broken JWT validation",
        "bad_deployment_changelog": "Updated JWT token validation and refresh logic",
        "bad_config": None,
        "red_herrings": [],
    },
    {
        "name": "search_service_oom",
        "root_cause_service": "search-service",
        "root_cause_category": "resource_exhaustion",
        "severity": "sev3",
        "affected_services": ["search-service", "product-service"],
        "correct_remediation": "restart",
        "alert_service": "search-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 5%",
        "alert_value": "15.8%",
        "alert_threshold": "5%",
        "description": "Search service OOM from unbounded query results",
        "bad_deployment_changelog": None,
        "bad_config": None,
        "red_herrings": [],
    },
]

MEDIUM_SCENARIOS = [
    {
        "name": "order_db_slow_query_cascade",
        "root_cause_service": "order-db",
        "root_cause_category": "database_issue",
        "severity": "sev2",
        "affected_services": ["order-db", "order-service", "api-gateway", "payment-service"],
        "correct_remediation": "hotfix",
        "alert_service": "api-gateway",
        "alert_metric": "latency_p99_ms",
        "alert_condition": "latency_p99 > 3000ms",
        "alert_value": "8542ms",
        "alert_threshold": "3000ms",
        "description": "Missing index causes slow queries cascading everywhere",
        "bad_deployment_changelog": "Added new API endpoint for bulk operations",
        "bad_config": None,
        "red_herrings": [{"service": "api-gateway", "clue": "Recent deploy (unrelated rate limiting)"}],
    },
    {
        "name": "config_pool_cascade",
        "root_cause_service": "user-service",
        "root_cause_category": "config_change",
        "severity": "sev2",
        "affected_services": ["user-service", "auth-service", "api-gateway"],
        "correct_remediation": "config_fix",
        "alert_service": "auth-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 5%",
        "alert_value": "18.7%",
        "alert_threshold": "5%",
        "description": "Connection pool reduced from 50 to 5",
        "bad_deployment_changelog": None,
        "bad_config": {"parameter": "db.connection_pool.max_size", "old_value": "50",
                       "new_value": "5", "reason": "resource optimization"},
        "red_herrings": [{"service": "auth-service", "clue": "Deploy 6h ago (unrelated)"}],
    },
    {
        "name": "payment_ext_cascade",
        "root_cause_service": "payment-gateway-ext",
        "root_cause_category": "dependency_failure",
        "severity": "sev1",
        "affected_services": ["payment-gateway-ext", "payment-service", "order-service", "api-gateway"],
        "correct_remediation": "escalate",
        "alert_service": "order-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 10%",
        "alert_value": "34.5%",
        "alert_threshold": "10%",
        "description": "External payment gateway outage cascading",
        "bad_deployment_changelog": None,
        "bad_config": None,
        "red_herrings": [{"service": "order-service", "clue": "Deploy 4h ago (fine until now)"}],
    },
    {
        "name": "elasticsearch_degradation",
        "root_cause_service": "elasticsearch",
        "root_cause_category": "resource_exhaustion",
        "severity": "sev3",
        "affected_services": ["elasticsearch", "search-service", "product-service"],
        "correct_remediation": "scale_up",
        "alert_service": "search-service",
        "alert_metric": "latency_p99_ms",
        "alert_condition": "latency_p99 > 1000ms",
        "alert_value": "3400ms",
        "alert_threshold": "1000ms",
        "description": "Elasticsearch heap pressure causing slow search",
        "bad_deployment_changelog": None,
        "bad_config": None,
        "red_herrings": [{"service": "product-service", "clue": "Cache miss rate up (consequence)"}],
    },
    {
        "name": "auth_timeout_cascade",
        "root_cause_service": "auth-service",
        "root_cause_category": "config_change",
        "severity": "sev2",
        "affected_services": ["auth-service", "user-service", "api-gateway"],
        "correct_remediation": "config_fix",
        "alert_service": "api-gateway",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 5%",
        "alert_value": "22.1%",
        "alert_threshold": "5%",
        "description": "Auth timeout changed from 30s to 1s",
        "bad_deployment_changelog": None,
        "bad_config": {"parameter": "upstream.timeout_seconds", "old_value": "30",
                       "new_value": "1", "reason": "performance tuning"},
        "red_herrings": [{"service": "user-service", "clue": "Memory at 65% (normal)"}],
    },
    {
        "name": "queue_overflow_cascade",
        "root_cause_service": "queue-rabbitmq",
        "root_cause_category": "resource_exhaustion",
        "severity": "sev2",
        "affected_services": ["queue-rabbitmq", "notification-service", "order-service"],
        "correct_remediation": "scale_up",
        "alert_service": "notification-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 10%",
        "alert_value": "42.3%",
        "alert_threshold": "10%",
        "description": "RabbitMQ queue full causing notification failures cascading to orders",
        "bad_deployment_changelog": None,
        "bad_config": None,
        "red_herrings": [{"service": "order-service", "clue": "Deploy 2h ago (unrelated)"}],
    },
    {
        "name": "product_db_replication_lag",
        "root_cause_service": "product-db",
        "root_cause_category": "database_issue",
        "severity": "sev3",
        "affected_services": ["product-db", "product-service", "search-service", "api-gateway"],
        "correct_remediation": "hotfix",
        "alert_service": "api-gateway",
        "alert_metric": "latency_p99_ms",
        "alert_condition": "latency_p99 > 2000ms",
        "alert_value": "4200ms",
        "alert_threshold": "2000ms",
        "description": "Product DB replication lag causing stale reads",
        "bad_deployment_changelog": None,
        "bad_config": None,
        "red_herrings": [{"service": "search-service", "clue": "ES CPU at 70% (normal indexing)"}],
    },
]

HARD_SCENARIOS = [
    {
        "name": "regex_cpu_burn",
        "root_cause_service": "product-service",
        "root_cause_category": "bad_deployment",
        "severity": "sev2",
        "affected_services": ["product-service", "api-gateway", "search-service"],
        "correct_remediation": "rollback",
        "alert_service": "api-gateway",
        "alert_metric": "latency_p99_ms",
        "alert_condition": "latency_p99 > 2000ms",
        "alert_value": "5230ms",
        "alert_threshold": "2000ms",
        "description": "Catastrophic regex backtracking in product-service input validation",
        "bad_deployment_changelog": "Updated regex patterns for input validation",
        "bad_config": None,
        "red_herrings": [
            {"service": "api-gateway", "clue": "High latency (symptom not cause)"},
            {"service": "search-service", "clue": "Latency elevated (downstream)"},
            {"service": "product-service", "clue": "Request rate normal — not traffic"},
        ],
    },
    {
        "name": "connection_pool_leak",
        "root_cause_service": "order-service",
        "root_cause_category": "memory_leak",
        "severity": "sev2",
        "affected_services": ["order-service", "order-db", "api-gateway", "payment-service"],
        "correct_remediation": "rollback",
        "alert_service": "order-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 5%",
        "alert_value": "15.3%",
        "alert_threshold": "5%",
        "description": "Connection pool leak — connections never returned. Memory grows over hours",
        "bad_deployment_changelog": "Refactored database connection pooling",
        "bad_config": None,
        "red_herrings": [
            {"service": "order-db", "clue": "Too many connections (symptom of leak)"},
            {"service": "api-gateway", "clue": "Errors elevated (cascading)"},
            {"service": "order-service", "clue": "CPU normal — issue is memory"},
        ],
    },
    {
        "name": "redis_config_with_deploy_herring",
        "root_cause_service": "cache-redis",
        "root_cause_category": "config_change",
        "severity": "sev1",
        "affected_services": ["cache-redis", "user-service", "product-service", "auth-service", "api-gateway"],
        "correct_remediation": "config_fix",
        "alert_service": "api-gateway",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 20%",
        "alert_value": "52.3%",
        "alert_threshold": "20%",
        "description": "Redis maxmemory-policy changed to noeviction. Coincidental user-service deploy",
        "bad_deployment_changelog": "Updated dependency versions (security patches)",
        "bad_config": {"parameter": "maxmemory-policy", "old_value": "allkeys-lru",
                       "new_value": "noeviction", "reason": "prevent eviction of cached sessions"},
        "red_herrings": [
            {"service": "user-service", "clue": "Deployed 30min ago (coincidence)"},
            {"service": "product-service", "clue": "Errors spiked (depends on redis)"},
        ],
    },
    {
        "name": "dns_intermittent",
        "root_cause_service": "user-service",
        "root_cause_category": "dns_failure",
        "severity": "sev1",
        "affected_services": ["user-service", "auth-service", "api-gateway"],
        "correct_remediation": "escalate",
        "alert_service": "api-gateway",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 15%",
        "alert_value": "38.9%",
        "alert_threshold": "15%",
        "description": "Intermittent DNS failure for user-service looks like app bug",
        "bad_deployment_changelog": None,
        "bad_config": None,
        "red_herrings": [
            {"service": "user-service", "clue": "Health checks pass sometimes (intermittent)"},
            {"service": "auth-service", "clue": "Errors look like user-service down"},
            {"service": "user-db", "clue": "DB perfectly healthy"},
        ],
    },
    {
        "name": "cert_expiry",
        "root_cause_service": "payment-service",
        "root_cause_category": "certificate_expiry",
        "severity": "sev1",
        "affected_services": ["payment-service", "order-service", "api-gateway"],
        "correct_remediation": "hotfix",
        "alert_service": "payment-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 10%",
        "alert_value": "100%",
        "alert_threshold": "10%",
        "description": "Internal TLS cert expired. All mTLS connections fail",
        "bad_deployment_changelog": None,
        "bad_config": None,
        "red_herrings": [
            {"service": "payment-gateway-ext", "clue": "External gateway is healthy"},
            {"service": "order-service", "clue": "Connection refused (symptom)"},
            {"service": "payment-service", "clue": "No recent deploys"},
        ],
    },
    {
        "name": "cascading_timeout_config",
        "root_cause_service": "api-gateway",
        "root_cause_category": "config_change",
        "severity": "sev1",
        "affected_services": ["api-gateway", "user-service", "order-service", "product-service"],
        "correct_remediation": "config_fix",
        "alert_service": "order-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 20%",
        "alert_value": "67.8%",
        "alert_threshold": "20%",
        "description": "API gateway timeout reduced from 30s to 2s killing all downstream requests",
        "bad_deployment_changelog": None,
        "bad_config": {"parameter": "global.request_timeout_seconds", "old_value": "30",
                       "new_value": "2", "reason": "reducing slow request impact"},
        "red_herrings": [
            {"service": "order-service", "clue": "Looks like order-service is crashing (gateway killing requests)"},
            {"service": "user-service", "clue": "Timeouts too (same cause)"},
            {"service": "product-service", "clue": "Recent deploy (unrelated)"},
        ],
    },
    {
        "name": "silent_cache_corruption",
        "root_cause_service": "cache-redis",
        "root_cause_category": "memory_leak",
        "severity": "sev2",
        "affected_services": ["cache-redis", "user-service", "product-service", "auth-service"],
        "correct_remediation": "restart",
        "alert_service": "user-service",
        "alert_metric": "error_rate",
        "alert_condition": "error_rate > 5%",
        "alert_value": "12.4%",
        "alert_threshold": "5%",
        "description": "Redis memory fragmentation causing silent cache corruption",
        "bad_deployment_changelog": None,
        "bad_config": None,
        "red_herrings": [
            {"service": "user-service", "clue": "Errors look like app bug (bad cache data)"},
            {"service": "auth-service", "clue": "Auth failures (also corrupt cache)"},
            {"service": "user-db", "clue": "DB perfectly healthy"},
        ],
    },
]


def generate_scenario(task_id: str, seed: int) -> dict:
    rng = random.Random(seed)

    if task_id == "easy_single_service_outage":
        template = rng.choice(EASY_SCENARIOS)
    elif task_id == "medium_cascading_failure":
        template = rng.choice(MEDIUM_SCENARIOS)
    elif task_id == "hard_subtle_degradation":
        template = rng.choice(HARD_SCENARIOS)
    elif task_id == "mixed_dynamic_incidents":
        # Randomly pick from ALL scenarios
        all_scenarios = EASY_SCENARIOS + MEDIUM_SCENARIOS + HARD_SCENARIOS
        template = rng.choice(all_scenarios)
    else:
        raise ValueError(f"Unknown task: {task_id}")
    infra = InfrastructureSimulator(seed=seed)
    infra.apply_incident_effects(
        root_cause_service=template["root_cause_service"],
        root_cause_category=template["root_cause_category"],
        affected_services=template["affected_services"],
        severity=template["severity"],
    )

    alert = Alert(
        alert_id=f"ALERT-{seed:06d}",
        timestamp=infra.base_time.strftime("%Y-%m-%dT%H:%M:%SZ"),
        service=template["alert_service"],
        metric=template["alert_metric"],
        condition=template["alert_condition"],
        current_value=template["alert_value"],
        threshold=template["alert_threshold"],
        severity_hint=template["severity"],
        description=f"Alert: {template['alert_condition']} on {template['alert_service']}",
    )

    return {
        "scenario_template": template,
        "infrastructure": infra,
        "alert": alert,
        "ground_truth": {
            "root_cause_service": template["root_cause_service"],
            "root_cause_category": template["root_cause_category"],
            "severity": template["severity"],
            "affected_services": template["affected_services"],
            "correct_remediation": template["correct_remediation"],
            "description": template["description"],
        },
        "bad_deployment_changelog": template.get("bad_deployment_changelog"),
        "bad_config": template.get("bad_config"),
        "red_herrings": template.get("red_herrings", []),
    }